#!/usr/bin/env python
"""gdprchecker CLI tool"""

import argparse
from checkers import https, forms


def main():
    """gdprchecker CLI tool entry point"""
    parser = argparse.ArgumentParser(description=(
        'Try to give hints about some steps required to make a website GDPR compliant. '
        'If no check flag is passed do all checks.'
    ))
    parser.add_argument('url', nargs='+', help='One or many urls to check')
    parser.add_argument('-f', '--form', action='store_true', help='Check for forms')
    parser.add_argument('-s', '--https', action='store_true', help='Check for https')
    parser.add_argument('--auth', help='Credentials for basic auth (user:passwd)')
    parser.add_argument('--no-crawl', action='store_false', dest='crawl',
                        help='Do not crawl the whole website, only check the given urls')
    parser.add_argument('--no-robotstxt', action='store_false', dest='robotstxt',
                        help='When crawling do not obey robots.txt')
    parser.add_argument('-v', action='count', default=0, dest='verbosity',
                        help='Increase the verbosity level')

    args = parser.parse_args()
    if not args.form and not args.https:
        args.form = True
        args.https = True

    if args.https:
        https.check(args.url)

    if args.form:
        forms.check(args.url, auth=args.auth, crawl=args.crawl,
                    robotstxt=args.robotstxt, verbosity=args.verbosity)


if __name__ == "__main__":
    main()
